### ISSUE TITLE
how to quickly reproduce you paper ?

### ISSUE THREAD

**Issue by carlhuang070** [lufficc/DPNet#2]
how to quickly reproduce you paper ?

**Comment by lufficc** [comment]
Use [refined masks](https://drive.google.com/drive/folders/1QqPQ0l7nDpIt8SnuUYWaYQU_8e_anHFc?usp=sharing) to synthesize images with [synthesize_images.py](https://isrc.iscas.ac.cn/gitlab/research/acm-mm-2019-ACO/blob/master/toolboxes/synthesize_images.py), and then render with [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) to get rendered images.

**Comment by edwardnguyen1705** [comment]
hi @lufficc ,
Do we need to train the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)?

**Comment by lufficc** [comment]
> hi @lufficc ,
> Do we need to train the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)?

Yes. You need to  train CycleGAN.

**Comment by edwardnguyen1705** [comment]
@lufficc ,
Thank you. I have another question, your paper states that you used coarse masks (low quality) as labels to train a Salient Object Detector, then used the trained detector to generate refined masks (high quality)?

I do not understand why it would be possible? In my opinion, labels should have higher quality than generated masks?

Could you give some suggestions?
