### ISSUE TITLE
which segmentation algorithm is better ?

### ISSUE THREAD

**Issue by carlhuang070** [lufficc/DPNet#3]
we can see Paper recommend use Salient Object Detection with CRF.
But from your source code ,we can inference you use traditional edge detection.

Do you know which is better?

**Comment by lufficc** [comment]
We first use traditional edge detection to extract coarse masks, and then use Salient Object Detection to refine the coarse masks. The refined masks can be downloaded here: https://drive.google.com/drive/folders/1QqPQ0l7nDpIt8SnuUYWaYQU_8e_anHFc?usp=sharing

**Comment by edwardnguyen1705** [comment]
Hi @lufficc ,
How could you train the salient object detector `https://github.com/AceCoooool/DSS-pytorch,` I mean which dataset you used to train the model?
